FROM debian

RUN apt-get update && apt-get upgrade -y && apt-get install curl python3 build-essential gcc make -y
RUN apt-get install libssl-dev pkg-config -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /home
ENV RUST_BACKTRACE=full

RUN cargo install --git https://github.com/RustPython/RustPython.git --features=ssl

ENTRYPOINT cargo build
